#DB ?? ??
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.demoju.mybatissample.dto